const projects = {
  cyprusinno: {
    title: "CyprusInno",
    subtitle: "Social media for entrepreneurs",
    intro:
      "Created a social platform for entrepreneurs, incorporating Laravel, Flutter, and Bootstrap, with features for networking, messaging, and event management, funded by the European Union.",
    files: [
      "App/edit_profile.png",
      "App/forgot_password.png",
      "App/login_screen.png",
      "App/message.png",
      "App/messages.png",
      "App/profile.png",
      "App/users.png",
      "Website/create_event_screen.png",
      "Website/create_user_screen.png",
      "Website/events_screen.png",
      "Website/homepage.png",
      "Website/login_screen.png",
      "Website/notification_screen.png",
      "Website/users_screen.png",
    ],
    descriptions: [
      "Secured funding from the European Union to support the project's development and implementation.",
      "Incorporated Bootstrap for frontend development and Laravel for backend functionalities.",
      "Utilised Flutter to build the mobile app version of Cyprusinno for both iOS and Android platforms.",
      "Designed and implemented features that allow users to search, follow, and message with other users.",
      "Developed an admin panel that enables organisation employees to manage users and company events effectively.",
      "Actively participated in project planning and regular meetings to ensure project objectives were met.",
    ],
    tags: ["laravel", "flutter", "bootstrap"],
  },
  eragps: {
    title: "GPS App",
    subtitle: "GPS Tracker for Shuttles",
    intro:
      "Built a Flutter app for real-time shuttle tracking on Google Maps using client-provided API endpoints.",
    files: ["eragps.gif"],
    descriptions: [
      "Developed a mobile application using Flutter to help users locate and track shuttles on Google Maps.",
      "API endpoints provided by the client for real-time shuttle location.",
    ],
    tags: ["flutter"],
  },
  gatsot: {
    title: "Gatsot",
    subtitle: "Smart Shopping Assistant",
    intro:
      "Created a smart shopping assistant app with crowdsourced pricing, integrating Laravel, Flutter, and Azure APIs, which earned €30,000 in funding for its innovation.",
    files: [],
    descriptions: [
      "Utilizing crowdsourcing algorithms to compile a comprehensive price database from various markets.",
      "Designed and developed a mobile application using Flutter with a Laravel-backed Rest API for querying prices, user authentication, and price data submission via receipt scanning.",
      "Integrated Azure API Services for text extraction from scanned images.",
      "Participated in the Startups4Peace startup competition, where our project garnered significant attention and appreciation, showcasing its potential impact and innovation in the market.",
      "Secured €30,000 in funding from government to support project development and implementation.",
      "Demo: https://www.youtube.com/watch?v=pqvS-y3KiQg",
    ],
    tags: ["laravel", "flutter"],
  },
  gurada: {
    title: "Gurada",
    subtitle: "Renting Platform",
    intro:
      "Developed a rental platform with Laravel and React, featuring search functionality, user reviews, and a responsive interface for seamless sharing experiences.",
    files: [
      "homepage.png",
      "item_page.png",
      "item_reviews.png",
      "login.png",
      "profile.png",
      "rentings.png",
      "requests.png",
    ],
    descriptions: [
      "Developed a website allowing individuals to rent out their belongings to others for accessibility and resource sharing.",
      "Implemented Laravel for backend development and React with Bootstrap for the frontend, ensuring robust functionality, efficient data management, and a responsive, visually appealing interface across devices.",
      "Integrated advanced search functionalities enabling users to browse items by name, price, date, and location.",
      "Enabled users to leave comments and ratings for rented items, fostering a community-driven platform.",
    ],
    tags: ["laravel", "bootstrap", "react"],
  },
  gymlog: {
    title: "GymLog",
    subtitle: "Gym Weight Journal",
    intro:
      "Designed a React Native gym log app, enabling users to track workout routines with an intuitive interface for both iOS and Android.",
    files: ["gymlog.gif", "new_set.png", "programs.png", "workout.png"],
    descriptions: [
      "Developed a mobile application using React Native, enabling users to track gym weights for each workout routine through a clean and intuitive interface, compatible with both iOS and Android devices.",
    ],
    tags: ["react-native"],
  },
  mesmer: {
    title: "Dental Clinic Portal",
    subtitle: "Application portal / Admin panel",
    intro:
      "Built a web application for dental clinics to manage item requests, featuring dynamic user roles, an admin panel, and streamlined workflows.",
    files: [
      "email_code.png",
      "forgot_password.png",
      "homepage.png",
      "login_screen.png",
      "new_order_1.png",
      "new_order_2.png",
      "new_organisation.png",
      "orders.png",
      "products.png",
      "rehearsals.png",
      "users.png",
    ],
    descriptions: [
      "Developed a web application to streamline dentists’ requests for specific dental items from client clinics.",
      "Designed dynamic user experiences, adapting the website based on user roles, with an admin panel for manage dentist accounts, oversee applications, and control pricing.",
      "Actively participated in planning and meetings to ensure alignment with project goals and timelines.",
    ],
    tags: ["laravel", "bootstrap"],
  },
  meather: {
    title: "Meather",
    subtitle: "Social Weather App",
    intro:
      "Developed a mobile application that combines real-time weather information with social networking features, enabling users to share and interact with weather-appropriate outfits.",
    files: [
      "meather_1.png",
      "meather_2.png",
      "meather_3.png",
      "meather_4.png",
      "meather_5.png",
      "meather_6.png",
      "meather_7.png",
      "meather_8.png",
    ],
    descriptions: [
      "Designed and developed the application using Flutter for the frontend, ensuring compatibility across iOS and Android devices.",
      "Built the backend using Laravel to manage user data, outfit uploads, and social interactions.",
      "Integrated real-time weather APIs to display accurate weather information for the user's current location or any location selected on a Google Maps interface.",
      "Implemented social features allowing users to upload outfits, and interact with other users by liking, commenting on posts, and following profiles.",
      "Utilised Google Maps to provide a dynamic and intuitive user interface for exploring weather and outfits in different cities worldwide.",
    ],
    tags: ["laravel", "flutter"],
  },
};
